"""Complete replacement of _build_draw_geometry_tab + all helpers.
Copy to WSL /tmp then run: python3 /tmp/full_v3.py
"""
path = '/home/shihuayue/codex_project/src/foamdesk/ui/main_window.py'

# Build the replacement code
NL = '\n'
replacement = NL + NL.join([
    '    def _build_draw_geometry_tab(self) -> QWidget:',
    '        wrapper = QWidget()',
    '        root_layout = QVBoxLayout(wrapper)',
    '        root_layout.setContentsMargins(0, 0, 0, 0)',
    '        root_layout.setSpacing(0)',
    '        scroll = QScrollArea()',
    '        scroll.setWidgetResizable(True)',
    '        scroll.setFrameShape(QFrame.Shape.NoFrame)',
    '        content = QWidget()',
    '        layout = QVBoxLayout(content)',
    '        layout.setContentsMargins(16, 16, 16, 16)',
    '        layout.setSpacing(10)',
    '',
    '        title = QLabel("绘制几何")',
    '        title.setStyleSheet("font-size: 22px; font-weight: 600;")',
    '        desc = QLabel("可视化编辑 blockMesh。计算域 + 几何体共用同一套顶点/边编辑。")',
    '        desc.setWordWrap(True)',
    '        layout.addWidget(title)',
    '        layout.addWidget(desc)',
    '',
    '        dv = [(0,0,0),(1,0,0),(1,1,0),(0,1,0),(0,0,1),(1,0,1),(1,1,1),(0,1,1)]',
    '        self._geo_objects = [{"name":"计算域","verts":list(dv),"edges":[],"block_v":[0,1,2,3,4,5,6,7],"is_domain":True,"nx":10,"ny":10,"nz":10,"grading":"1 1 1"}]',
    '        self._active_obj_idx = 0',
    '',
    '        obj_row = QHBoxLayout()',
    '        obj_row.setSpacing(8)',
    '        self._obj_combo = QComboBox()',
    '        self._obj_combo.currentIndexChanged.connect(self._switch_active_object)',
    '        new_btn = QPushButton("+ 新建几何体")',
    '        new_btn.clicked.connect(self._new_geo_object)',
    '        del_btn = QPushButton("- 删除当前")',
    '        del_btn.clicked.connect(self._delete_geo_object)',
    '        obj_row.addWidget(QLabel("编辑对象"))',
    '        obj_row.addWidget(self._obj_combo, 1)',
    '        obj_row.addWidget(new_btn)',
    '        obj_row.addWidget(del_btn)',
    '        layout.addLayout(obj_row)',
    '        self._rebuild_obj_combo()',
    '',
    '        vh = QHBoxLayout()',
    '        vh.addWidget(QLabel("顶点列表"))',
    '        add_v = QPushButton("+ 添加")',
    '        del_v = QPushButton("- 删除")',
    '        vh.addStretch(1); vh.addWidget(add_v); vh.addWidget(del_v)',
    '        layout.addLayout(vh)',
    '',
    '        self._vertex_table = QTableWidget(0, 3)',
    '        self._vertex_table.setHorizontalHeaderLabels(["X", "Y", "Z"])',
    '        self._vertex_table.horizontalHeader().setStretchLastSection(True)',
    '        self._vertex_table.setMinimumHeight(180)',
    '        self._vertex_table.cellChanged.connect(self._on_vertex_table_changed)',
    '        add_v.clicked.connect(lambda: (self._add_vertex_row(0,0,0), self._save_vertex_table(), self._refresh_draw_geo_preview()))',
    '        del_v.clicked.connect(self._delete_selected_vertex)',
    '        layout.addWidget(self._vertex_table)',
    '',
    '        elab = QLabel("边 (Edges)")',
    '        elab.setStyleSheet("font-weight: 600; margin-top: 8px;")',
    '        layout.addWidget(elab)',
    '        ef = QHBoxLayout(); ef.setSpacing(6)',
    '        self._edge_type_combo = QComboBox()',
    '        self._edge_type_combo.addItems(["arc","spline","polyLine","BSpline"])',
    '        self._edge_start = QSpinBox(); self._edge_start.setRange(0,99); self._edge_start.setValue(0)',
    '        self._edge_end = QSpinBox(); self._edge_end.setRange(0,99); self._edge_end.setValue(1)',
    '        self._edge_interp = QLineEdit("0.5 0.5 0.5")',
    '        self._edge_interp.setPlaceholderText("x y z")',
    '        self._edge_interp.setMinimumWidth(160)',
    '        ae = QPushButton("添加边")',
    '        ae.clicked.connect(self._add_edge_to_current)',
    '        ef.addWidget(QLabel("类型")); ef.addWidget(self._edge_type_combo)',
    '        ef.addWidget(QLabel("起点")); ef.addWidget(self._edge_start)',
    '        ef.addWidget(QLabel("终点")); ef.addWidget(self._edge_end)',
    '        ef.addWidget(QLabel("插值点")); ef.addWidget(self._edge_interp)',
    '        ef.addWidget(ae); ef.addStretch(1)',
    '        layout.addLayout(ef)',
    '',
    '        self._edge_list = QTextEdit()',
    '        self._edge_list.setReadOnly(True); self._edge_list.setMaximumHeight(80)',
    '        self._edge_list.setPlaceholderText("当前对象的边显示在这里。")',
    '        layout.addWidget(self._edge_list)',
    '        de_btn = QPushButton("删除选中边")',
    '        de_btn.clicked.connect(self._delete_selected_edge)',
    '        layout.addWidget(de_btn)',
    '        self._edge_defs = []',
    '',
])
# Too long for Write tool. This approach won't scale.
print("See - this file is incomplete. Need a different strategy.")
print('Partial built length:', len(replacement))
