"""One-shot replacement for draw geometry page. Pipe to: wsl -d Ubuntu -e python3 < this_file"""
path = '/home/shihuayue/codex_project/src/foamdesk/ui/main_window.py'
with open(path) as f:
    c = f.read()

start = c.find('    def _build_draw_geometry_tab(self) -> QWidget:')
end = c.find('\n    def _build_geometry_tab(self) -> QWidget:')

# Build the replacement code directly
nl = '\n'
replacement = nl + nl.join([
    '    def _build_draw_geometry_tab(self) -> QWidget:',
    '        wrapper = QWidget()',
    '        root_layout = QVBoxLayout(wrapper)',
    '        root_layout.setContentsMargins(0, 0, 0, 0)',
    '        root_layout.setSpacing(0)',
    '        scroll = QScrollArea()',
    '        scroll.setWidgetResizable(True)',
    '        scroll.setFrameShape(QFrame.Shape.NoFrame)',
    '        content = QWidget()',
    '        layout = QVBoxLayout(content)',
    '        layout.setContentsMargins(16, 16, 16, 16)',
    '        layout.setSpacing(10)',
    '',
    '        title = QLabel("绘制几何")',
    '        title.setStyleSheet("font-size: 22px; font-weight: 600;")',
    '        desc = QLabel("可视化编辑 blockMesh。计算域 + 几何体共用同一套顶点/边编辑。")',
    '        desc.setWordWrap(True)',
    '        layout.addWidget(title)',
    '        layout.addWidget(desc)',
    '',
    '        dv = [(0,0,0),(1,0,0),(1,1,0),(0,1,0),(0,0,1),(1,0,1),(1,1,1),(0,1,1)]',
    '        self._geo_objects = [{"name":"计算域","verts":list(dv),"edges":[],"block_v":[0,1,2,3,4,5,6,7],"is_domain":True,"nx":10,"ny":10,"nz":10,"grading":"1 1 1"}]',
    '        self._active_obj_idx = 0',
    '',
    '        obj_row = QHBoxLayout()',
    '        obj_row.setSpacing(8)',
    '        self._obj_combo = QComboBox()',
    '        self._obj_combo.currentIndexChanged.connect(self._switch_active_object)',
    '        new_btn = QPushButton("+ 新建几何体")',
    '        new_btn.clicked.connect(self._new_geo_object)',
    '        del_btn = QPushButton("- 删除当前")',
    '        del_btn.clicked.connect(self._delete_geo_object)',
    '        obj_row.addWidget(QLabel("编辑对象"))',
    '        obj_row.addWidget(self._obj_combo, 1)',
    '        obj_row.addWidget(new_btn)',
    '        obj_row.addWidget(del_btn)',
    '        layout.addLayout(obj_row)',
    '        self._rebuild_obj_combo()',
    '',
    '        vh = QHBoxLayout()',
    '        vh.addWidget(QLabel("顶点列表"))',
    '        add_v = QPushButton("+ 添加")',
    '        del_v = QPushButton("- 删除")',
    '        vh.addStretch(1); vh.addWidget(add_v); vh.addWidget(del_v)',
    '        layout.addLayout(vh)',
    '',
    '        self._vertex_table = QTableWidget(0, 3)',
    '        self._vertex_table.setHorizontalHeaderLabels(["X", "Y", "Z"])',
    '        self._vertex_table.horizontalHeader().setStretchLastSection(True)',
    '        self._vertex_table.setMinimumHeight(180)',
    '        self._vertex_table.cellChanged.connect(self._on_vertex_table_changed)',
    '        add_v.clicked.connect(lambda: (self._add_vertex_row(0,0,0), self._save_vertex_table(), self._refresh_draw_geo_preview()))',
    '        del_v.clicked.connect(self._delete_selected_vertex)',
    '        layout.addWidget(self._vertex_table)',
    '',
    '        elab = QLabel("边 (Edges)")',
    '        elab.setStyleSheet("font-weight: 600; margin-top: 8px;")',
    '        layout.addWidget(elab)',
    '        ef = QHBoxLayout(); ef.setSpacing(6)',
    '        self._edge_type_combo = QComboBox()',
    '        self._edge_type_combo.addItems(["arc","spline","polyLine","BSpline"])',
    '        self._edge_start = QSpinBox(); self._edge_start.setRange(0,99); self._edge_start.setValue(0)',
    '        self._edge_end = QSpinBox(); self._edge_end.setRange(0,99); self._edge_end.setValue(1)',
    '        self._edge_interp = QLineEdit("0.5 0.5 0.5")',
    '        self._edge_interp.setPlaceholderText("x y z")',
    '        self._edge_interp.setMinimumWidth(160)',
    '        ae = QPushButton("添加边")',
    '        ae.clicked.connect(self._add_edge_to_current)',
    '        ef.addWidget(QLabel("类型")); ef.addWidget(self._edge_type_combo)',
    '        ef.addWidget(QLabel("起点")); ef.addWidget(self._edge_start)',
    '        ef.addWidget(QLabel("终点")); ef.addWidget(self._edge_end)',
    '        ef.addWidget(QLabel("插值点")); ef.addWidget(self._edge_interp)',
    '        ef.addWidget(ae); ef.addStretch(1)',
    '        layout.addLayout(ef)',
    '',
    '        self._edge_list = QTextEdit()',
    '        self._edge_list.setReadOnly(True); self._edge_list.setMaximumHeight(80)',
    '        self._edge_list.setPlaceholderText("当前对象的边显示在这里。")',
    '        layout.addWidget(self._edge_list)',
    '        de_btn = QPushButton("删除选中边")',
    '        de_btn.clicked.connect(self._delete_selected_edge)',
    '        layout.addWidget(de_btn)',
    '        self._edge_defs = []',
    '',
    '        self._block_widget = QWidget()',
    '        blk = QVBoxLayout(self._block_widget)',
    '        blk.setContentsMargins(0,0,0,0); blk.setSpacing(6)',
    '        bl = QLabel("块 (Blocks)")',
    '        bl.setStyleSheet("font-weight: 600;")',
    '        blk.addWidget(bl)',
    '        br = QHBoxLayout(); br.setSpacing(6)',
    '        self._block_vert_inputs = []',
    '        for i in range(8):',
    '            sb = QSpinBox(); sb.setRange(0,99); sb.setValue(i)',
    '            sb.valueChanged.connect(self._on_block_vert_changed)',
    '            self._block_vert_inputs.append(sb)',
    '            br.addWidget(QLabel(str(i))); br.addWidget(sb)',
    '        br.addStretch(1)',
    '        blk.addLayout(br)',
    '',
    '        cr = QHBoxLayout(); cr.setSpacing(8)',
    '        self._geo_nx = QSpinBox(); self._geo_nx.setRange(1,500); self._geo_nx.setValue(10)',
    '        self._geo_ny = QSpinBox(); self._geo_ny.setRange(1,500); self._geo_ny.setValue(10)',
    '        self._geo_nz = QSpinBox(); self._geo_nz.setRange(1,500); self._geo_nz.setValue(10)',
    '        for w in (self._geo_nx,self._geo_ny,self._geo_nz):',
    '            w.valueChanged.connect(self._on_cell_changed); w.setMinimumWidth(80)',
    '        cr.addWidget(QLabel("Nx")); cr.addWidget(self._geo_nx)',
    '        cr.addWidget(QLabel("Ny")); cr.addWidget(self._geo_ny)',
    '        cr.addWidget(QLabel("Nz")); cr.addWidget(self._geo_nz)',
    '        self._geo_grading = QLineEdit("1 1 1")',
    '        self._geo_grading.setMaximumWidth(120)',
    '        self._geo_grading.textChanged.connect(self._on_grading_changed)',
    '        cr.addWidget(QLabel("Grading")); cr.addWidget(self._geo_grading)',
    '        cr.addStretch(1)',
    '        blk.addLayout(cr)',
    '        layout.addWidget(self._block_widget)',
    '',
    '        self._boundary_widget = QWidget()',
    '        bnr = QHBoxLayout(self._boundary_widget)',
    '        bnr.setContentsMargins(0,0,0,0); bnr.setSpacing(8)',
    '        bnr.addWidget(QLabel("入口"))',
    '        self._geo_inlet = QLineEdit("inlet"); bnr.addWidget(self._geo_inlet)',
    '        bnr.addWidget(QLabel("出口"))',
    '        self._geo_outlet = QLineEdit("outlet"); bnr.addWidget(self._geo_outlet)',
    '        bnr.addWidget(QLabel("壁面"))',
    '        self._geo_walls = QLineEdit("fixedWalls"); bnr.addWidget(self._geo_walls)',
    '        bnr.addStretch(1)',
    '        layout.addWidget(self._boundary_widget)',
    '',
    '        self._geo_preview_fig = Figure(figsize=(6.8, 3.5), facecolor="#1e1e1e", tight_layout=True)',
    '        self._geo_preview_canvas = FigureCanvas(self._geo_preview_fig)',
    '        self._geo_preview_canvas.setMinimumHeight(380)',
    '        layout.addWidget(self._geo_preview_canvas)',
    '',
    '        br2 = QHBoxLayout(); br2.setSpacing(8)',
    '        gb = QPushButton("生成 blockMeshDict + STL")',
    '        gb.clicked.connect(lambda _checked=False: self._apply_draw_geometry())',
    '        rb = QPushButton("重置全部")',
    '        rb.clicked.connect(lambda _checked=False: self._reset_draw_geometry())',
    '        br2.addWidget(gb); br2.addWidget(rb); br2.addStretch(1)',
    '        layout.addLayout(br2)',
    '',
    '        layout.addStretch(1)',
    '        scroll.setWidget(content)',
    '        root_layout.addWidget(scroll)',
    '        self._load_active_object_to_ui()',
    '        self._refresh_draw_geo_preview()',
    '        return wrapper',
])

c = c[:start] + replacement + c[end:]
with open(path, 'w') as f:
    f.write(c)
print('OK - build tab replaced')
